### ISSUE TITLE
"AttributeError: 'FfsClient' object has no attribute 'get_file_bytes'"

### ISSUE THREAD

**Issue by peterVG** [pygate/pygate-gRPC#23]
This is a regression generated by line 17 https://github.com/pygate/pygate-gRPC/blob/8d875b000888539aa4ec0faa4526dad07fbb910c/examples/ffs_push_pull_file.py#L17 in examples/ffs_push_pull_file.py

**Comment by peterVG** [comment]
Actually, this error only occurs when I run the script from `pipenv shell`. I've installed all the dependencies in a virtualenv and it works fine. So maybe `pipfile` needs an update?

**Comment by leonardge** [comment]
I have moved the `get_file_bytes` from an instance method of `ffs` to a separate helper method. So maybe we're using a later version of the package?
