### ISSUE TITLE
ffs.default_config does not return all Config attributes

### ISSUE THREAD

**Issue by peterVG** [pygate/pygate-gRPC#30]
See https://github.com/pygate/pygate-gRPC/blob/main/pygate_grpc/ffs.py#L73-L75

If you run the examples script which uses this function (see https://github.com/pygate/pygate-gRPC/blob/main/examples/ffs_config.py), it outputs the following attributes for the Config:

<img width="753" alt="Screen Shot 2020-08-02 at 8 02 58 PM" src="https://user-images.githubusercontent.com/672121/89142054-3b00a800-d4fb-11ea-8693-9ba092f01347.png">

However, if you use the same FFS and token and run it in CLI you get:

<img width="1087" alt="Screen Shot 2020-08-02 at 8 04 30 PM" src="https://user-images.githubusercontent.com/672121/89142116-68e5ec80-d4fb-11ea-8c71-5c58373ffc9f.png">

Specifically the following fields are missing from the pygate ffs.default_config:

from "Hot":
- "AllowUnfreeze"

from "Cold":
- "ExcludedMiners"
- "TrustedMiners"
- "CountryCodes"
- "Renew" - "Enabled"
- "Renew" - "Threshold"
- "MaxPrice"
- "Repairable"

Also, "Pinned CIDs"

Also of note is that the Powergate CLI output used PascalCase wherease the Pygate output uses snake_case, is this for PEP 8 compliance?

**Comment by 524119574** [comment]
I think the fields are missing because it's using default value. Specifically: `false` (for boolean), `null` (for object), `0` (for number).

**Comment by 524119574** [comment]
>Also of note is that the Powergate CLI output used PascalCase wherease the Pygate output uses snake_case, is this for PEP 8 compliance?
I think it's because the generated code is language-specific, the CLI is written in Go, so it's using Pascal case (public field in Go has to start with a capital letter) while we are using Python.

**Comment by 524119574** [comment]
You can test this by setting the default configuration, for example set the `repairable` to be `true` and it should appear.

**Comment by peterVG** [comment]
Yes, I've tested and confirmed this. If the "missing" attributes are assigned values and pushed to a new defaultConfig they will display.
